### ISSUE TITLE
Generate.py cant work with my images

### ISSUE THREAD

**Issue by MJGames** [LucasBerbesson/pixelstick#1]
The python script can work with any other image then the demo image in de documentation folder. I try everything, but nothing work.

**Comment by LucasBerbesson** [comment]
Hello, can you detail the error you get ?

**Comment by MJGames** [comment]
I solved the problem that the python script get all 4 variable for pixel. Simply add an alpha channel to get brightness. The problem now is that arduino don't "print" the right color into the strip. I have only 30 led and i think there is a problem with this.

**Comment by LucasBerbesson** [comment]
Yes, you need to change the 
`int number_of_leds = 30` variable in the `.ino` file and you need to make sure the image you converted with the python script is exactly 30 pixels high.

**Comment by MJGames** [comment]
there is really something wrong with the colors. They are never correct.

**Comment by MJGames** [comment]
I done this

**Comment by LucasBerbesson** [comment]
The problem can also come from your LED Strip

**Comment by MJGames** [comment]
ahh, i think u are right

**Comment by MJGames** [comment]
wait a sec i test another strip where i know that the led are WS2812B

**Comment by MJGames** [comment]
ok the colors are now correct, but my blue line i draw goes on every position.
![unbenannt](https://user-images.githubusercontent.com/7645364/30270775-2e633bba-96ee-11e7-9d9c-7e12341452a3.png)

**Comment by MJGames** [comment]
like this
![unbenannt1](https://user-images.githubusercontent.com/7645364/30270862-6e137d74-96ee-11e7-9d91-8b28ee62d44b.png)

**Comment by MJGames** [comment]
ok i had a problem with the image and the led and now is everything fixed. sry for asking so badly. The project is very nice and simply to understand(if ur not a fully retard)

**Comment by LucasBerbesson** [comment]
Ok great well done !
