### ISSUE TITLE
Generate.py issue 

### ISSUE THREAD

**Issue by molynknow** [LucasBerbesson/pixelstick#3]
Hi so far i have been able to follow your tutorial and its been really simple. I don't have any python or experience or much coding experience at all so your step by step instructions have been really helpful. The issue i keep running into is i keep getting an error on line 10:

`from PIL import Image`

saying there is no module named PIL

Am I missing something?

Thanks in advance,

Alex

**Comment by LucasBerbesson** [comment]
You need to install PIL.
run `pip install Pillow`from a terminal

**Comment by molynknow** [comment]
Thanks for the quick response, I will try it and let you know!

**Comment by molynknow** [comment]
It worked out thanks for the help
