### ISSUE TITLE
generate.py problème

### ISSUE THREAD

**Issue by batlepirate** [LucasBerbesson/pixelstick#6]
Salut Lucas,

Merci pour ton tuto, ca faisait longtemps que je cherchais a fabriquer un pixelstick fiable.

J'ai des soucis pour générer le fichier TXT correspondant à l'image PNG un message d'erreur apparait quand je le lance:

Traceback (most recent call last):
  File "C:\Users\bat\Desktop\PixelStick\documentation\generate.py", line 16, in <module>
    im = Image.open(filename)
NameError: name 'Image' is not defined

Je n'y connais absolument rien en arduino et encore moins en python...
J'ai réussi tant bien que mal a installer la librairie pil ou pillow.

J'ai essayé plusieurs solutions et recherches mais je reste bloqué je ne comprends rien malgré mes efforts... Pourrais-tu m'éclairer?

Merci,

Bat.

**Comment by LucasBerbesson** [comment]
Salut Bat.
Est-ce que tu as bien installé la librairie PIL 
Il lancer la commande `pip install PIL` depuis un terminal je crois

**Comment by batlepirate** [comment]
Oui c'est bon, j'ai trouvé la commande dans un autre post. Merci!
